name: Auto Update News Sitemap

on:
  schedule:
    - cron: '0 4 * * *'    # 12:00 WITA
    - cron: '5 8 * * *'    # 16:05 WITA
    - cron: '0 11 * * *'   # 19:00 WITA
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser pytz

      - name: Generate news-sitemap.xml
        run: python generate.py

            - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add news-sitemap.xml
          git commit -m "Auto update news sitemap" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
